### ISSUE TITLE
Remove the icon in each possible input field

### ISSUE THREAD

**Issue by mschiek** [braden-w/whispering#114] opened 2024-06-25 14:02 UTC
Hi Braden. 
Thanks for this awesome extension! It saves me hours each week.

with the new update is there a way to hide that "microphone" icon in websites? 
These appear in all sorts of places (on sticky notes on a whiteboard app for example) and are a bit intrusive.

Maybe a temporary fix via a css filter e.g.? Maybe this could be set in the settings.

Thanks

**Comment by OLH21** [comment] 2024-06-25 14:23
You can just add or remove access to any site in the extension option as for any other chrome extension, by default i assume it has acces to all the site but you can restrain to the site you want only. thus you are in control ;)

**Comment by Wstnn** [comment] 2024-06-25 16:26
I only want to remove the icon itself without losing the base functionality.

**Comment by braden-w** [comment] 2024-06-29 21:16
Sorry for the inconvenience @mschiek , this was caused by an accidental push to the Chrome Web store while I was playing around with an automation!

I have closed this in #124 and we are waiting for Chrome Web Store to approve it. The icon should now only show up in ChatGPT and Anthropic as a temporary fix.

In the meantime, feel free to disable the extension. Apologies for the inconvenience!

**Closed by braden-w** 2024-06-29 21:16 UTC
